#                                       Avance II Proyecto Final
#### Equipo #3
#### Grupo: 006 
#### Frecuencia : Lunes, Miercoles,Viernes  6-7 pm
#### Integrantes : 
* Francisco Ramon Ramirez Torres 1739900. 
* Cesar Gerardo Varela Cavazos 1748727. 
* Cesar Alejandro Barrera Martinez 1618509

### 1. Limpieza de datos

In [1]:
import numpy as np
import pandas as pd
import json
import seaborn as sn
import pandas_profiling 
import matplotlib.pyplot as plt

%matplotlib inline

C:\Users\Franc\Anaconda3\lib\site-packages\statsmodels\tools\_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

* importacion de librerias

In [2]:
df = pd.read_csv("train.csv")

* Con esta variable df la usaremos para abrir nuestra BD

###### a)	Mostrar los datos sin manipulaci√≥n

In [3]:
df.head()

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
0,Rapala Trophies,PSP,2006.0,Sports,Activision,0.04,0.00,0.00,0.00,NaN,NaN,NaN,NaN,Sand Grain Studios,E
1,New Super Mario Bros. U,WiiU,2012.0,Platform,Nintendo,2.30,1.34,1.27,0.32,84.0,70.0,8.1,733.0,Nintendo,E
2,Robots,PS2,2005.0,Action,Vivendi Games,0.18,0.14,0.00,0.05,53.0,6.0,6.0,8.0,Eurocom Entertainment Software,E
3,Hamster Club 3,GBA,2002.0,Simulation,Jorudan,0.00,0.00,0.35,0.01,NaN,NaN,NaN,NaN,NaN,NaN
4,Formula 1 06,PS2,2006.0,Racing,Sony Computer Entertainment,0.00,0.00,0.04,0.00,NaN,NaN,NaN,NaN,NaN,NaN

* Usamos la funcion head() para mostrar los primeros 5 registros solo para revisar si cargo correctamente

In [4]:
df.tail()

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
11698,Call of Duty: Black Ops,X360,2010.0,Shooter,Activision,9.70,3.68,0.11,1.13,87.0,89.0,6.3,1454.0,Treyarch,M
11699,Resistance 3,PS3,2011.0,Shooter,Sony Computer Entertainment,0.64,0.57,0.05,0.22,83.0,91.0,7.8,543.0,Insomniac Games,M
11700,Ready 2 Rumble Revolution,Wii,2009.0,Sports,Atari,0.15,0.00,0.00,0.01,37.0,31.0,NaN,NaN,10tacle Studios,T
11701,Monster Hunter Frontier Online: Forward 2,X360,2011.0,Role-Playing,Capcom,0.00,0.00,0.03,0.00,NaN,NaN,NaN,NaN,NaN,NaN
11702,NHL 2K9,PS3,2008.0,Sports,Take-Two Interactive,0.11,0.01,0.00,0.01,70.0,21.0,NaN,NaN,Visual Concepts,E10+

* Usamos la funcion tail() para mostrar los primeros 5 registros solo para revisar si cargo correctamente

###### b)	Eliminar columnas no deseadas.

In [6]:
df.drop(['User_Count', 'User_Score', 'Critic_Count','Critic_Score','Developer'], axis=1)

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Rating
0,Rapala Trophies,PSP,2006.0,Sports,Activision,0.04,0.00,0.00,0.00,E
1,New Super Mario Bros. U,WiiU,2012.0,Platform,Nintendo,2.30,1.34,1.27,0.32,E
2,Robots,PS2,2005.0,Action,Vivendi Games,0.18,0.14,0.00,0.05,E
3,Hamster Club 3,GBA,2002.0,Simulation,Jorudan,0.00,0.00,0.35,0.01,NaN
4,Formula 1 06,PS2,2006.0,Racing,Sony Computer Entertainment,0.00,0.00,0.04,0.00,NaN
...,...,...,...,...,...,...,...,...,...,...
11698,Call of Duty: Black Ops,X360,2010.0,Shooter,Activision,9.70,3.68,0.11,1.13,M
11699,Resistance 3,PS3,2011.0,Shooter,Sony Computer Entertainment,0.64,0.57,0.05,0.22,M
11700,Ready 2 Rumble Revolution,Wii,2009.0,Sports,Atari,0.15,0.00,0.00,0.01,T
11701,Monster Hunter Frontier Online: Forward 2,X360,2011.0,Role-Playing,Capcom,0.00,0.00,0.03,0.00,NaN
11702,NHL 2K9,PS3,2008.0,Sports,Take-Two Interactive,0.11,0.01,0.00,0.01,E10+

* Eliminamos algunas columnas que no nos ayudan tanto ya que muchos datos eran vacios o NaN y no nos serviria hacer analisis de datos vacios

###### c)	Correcta manipulaci√≥n de los datos nulos dentro de la base de datos.